_badp_login:
  defaults:     { _controller: "MvBlogBundle:AdminBlog/Secured:login" }
  pattern:      "/login"
  
_badp_logout:
  defaults:     { _controller: "MvBlogBundle:AdminBlog/Secured:logout" }
  pattern:      "/logout"
  
_badp_security_check:
  defaults:     { _controller: "MvBlogBundle:AdminBlog/Secured:securityCheck" }
  pattern:      "/login_check"